### ISSUE TITLE
coze api未找到

### ISSUE THREAD

**Issue by SS-snap** [SoftMeng/ComfyUI-Coze#1]
发布的时候没有找到coze API
![微信截图_20240621104529](https://github.com/SoftMeng/ComfyUI-Coze/assets/143506979/6845167b-3705-4e64-854f-4757c56c9026)

**Comment by SoftMeng** [comment]
参考官方的文档，先创建个人令牌，并保存好：https://www.coze.cn/docs/developer_guides/authentication
